version: '3'
services:
  rabbitmq:
    image: library/rabbitmq:3-management
    networks:
       asujs-network:
         aliases:
           - rabbitmq
    deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 30
            window: 20s
    ports:
      - 15672:15672
      - 5672:5672
      
  config:
    environment:
      CONFIG_SERVICE_PASSWORD: "test"
    image: sqshq/piggymetrics-config:latest
    networks:
       asujs-network:
         aliases:
           - config
    hostname: config
    deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 30
            window: 20s

    ports:
      - 8888:8888


  registry:
    environment:
      CONFIG_SERVICE_PASSWORD: "test"
    image: sqshq/piggymetrics-registry:latest
    networks:
       asujs-network:
         aliases:
           - registry
    deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 30
            window: 20s

    ports:
      - 8761:8761



  gateway:
    environment:
      CONFIG_SERVICE_PASSWORD: "test"
    image: sqshq/piggymetrics-gateway:latest
    networks:
       asujs-network:
         aliases:
           - gateway
    deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 30
            window: 20s

    ports:
      - 8081:4000

  auth-service:
    environment:
      CONFIG_SERVICE_PASSWORD: "test"
      NOTIFICATION_SERVICE_PASSWORD: "test"
      STATISTICS_SERVICE_PASSWORD: "test"
      ACCOUNT_SERVICE_PASSWORD: "test"
      MONGODB_PASSWORD: "test"
    image: sqshq/piggymetrics-auth-service:latest
    networks:
       asujs-network:
         aliases:
           - auth-service
    deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 30
            window: 20s

    ports:
      - 5000:5000



  auth-mongodb:
    environment:
      MONGODB_PASSWORD: "test"
    image: sqshq/piggymetrics-mongodb:latest
    networks:
       asujs-network:
         aliases:
           - auth-mongodb
    deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 30
            window: 20s

    ports:
      - 25000:27017
    links:
      - config


  account-service:
    environment:
      CONFIG_SERVICE_PASSWORD: "test"
      ACCOUNT_SERVICE_PASSWORD: "test"
      MONGODB_PASSWORD: "test"
    image: sqshq/piggymetrics-account-service:latest
    networks:
       asujs-network:
         aliases:
           - account-service
    deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 30
            window: 20s

    ports:
      - 6000:6000
 


  account-mongodb:
    environment:
      INIT_DUMP: account-service-dump.js
      MONGODB_PASSWORD: "test"
    image: sqshq/piggymetrics-mongodb:latest
    networks:
       asujs-network:
         aliases:
           - account-mongodb
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 30
        window: 20s
    ports:
      - 26000:27017


  statistics-service:
    environment:
      CONFIG_SERVICE_PASSWORD: "test"
      MONGODB_PASSWORD: "test"
      STATISTICS_SERVICE_PASSWORD: "test"
    image: sqshq/piggymetrics-statistics-service:latest
    networks:
       asujs-network:
         aliases:
           - statistics-service

    deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 30
            window: 20s

    ports:
      - 7000:7000
    depends_on:
       - config



  statistics-mongodb:
    environment:
      MONGODB_PASSWORD: "test"
    image: sqshq/piggymetrics-mongodb:latest
    networks:
       asujs-network:
         aliases:
           - statistics-mongodb

    deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 30
            window: 20s

    ports:
      - 27000:27017
 

  notification-service:
    environment:
      CONFIG_SERVICE_PASSWORD: "test"
      MONGODB_PASSWORD: "test"
      NOTIFICATION_SERVICE_PASSWORD: "test"
    image: sqshq/piggymetrics-notification-service:latest
    networks:
       asujs-network:
         aliases:
           - notification-service

    deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 30
            window: 20s

    ports:
      - 8000:8000
   



  notification-mongodb:
    image: sqshq/piggymetrics-mongodb:latest
    networks:
       asujs-network:
         aliases:
           - notification-mongodb

    deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 30
            window: 20s

    environment:
      MONGODB_PASSWORD: "test"
    ports:
      - 28000:27017

  monitoring:
    environment:
      CONFIG_SERVICE_PASSWORD: "test"
    image: sqshq/piggymetrics-monitoring:latest
    networks:
       asujs-network:
         aliases:
           - monitoring
    deploy:
          restart_policy:
            condition: on-failure
            delay: 5s
            max_attempts: 30
            window: 20s


    ports:
      - 9000:8080
      - 8989:8989
   

networks:
 asujs-network:
  driver: overlay
